In [1]:
%matplotlib notebook
%load_ext autoreload
%autoreload 2
import cv2
import numpy as np
import matplotlib.pyplot as plt
from utils import *
import student_code as sc

In [2]:
# Load the data
points_2d = np.loadtxt('../data/pts2d-norm-pic_a.txt')
points_3d = np.loadtxt('../data/pts3d-norm.txt')

# (Optional) Uncomment these four lines once you have your code working with the easier, normalized points above.
# points_2d = np.loadtxt('../data/pts2d-norm-pic_b.txt')
# points_3d = np.loadtxt('../data/pts3d.txt')

In [4]:
points_2d

array([[ 1.0486, -0.3645],
       [-1.6851, -0.4004],
       [-0.9437, -0.42  ],
       [ 1.0682,  0.0699],
       [ 0.6077, -0.0771],
       [ 1.2543, -0.6454],
       [-0.2709,  0.8635],
       [-0.4571, -0.3645],
       [-0.7902,  0.0307],
       [ 0.7318,  0.6382],
       [-1.058 ,  0.3312],
       [ 0.3464,  0.3377],
       [ 0.3137,  0.1189],
       [-0.431 ,  0.0242],
       [-0.4799,  0.292 ],
       [ 0.6109,  0.083 ],
       [-0.4081,  0.292 ],
       [-0.1109, -0.2992],
       [ 0.5129, -0.0575],
       [ 0.1406, -0.4527]])

In [5]:
points_3d

array([[ 1.5706, -0.149 ,  0.2598],
       [-1.5282,  0.9695,  0.3802],
       [-0.6821,  1.2856,  0.4078],
       [ 0.4124, -1.0201, -0.0915],
       [ 1.2095,  0.2812, -0.128 ],
       [ 0.8819, -0.8481,  0.5255],
       [-0.9442, -1.1583, -0.3759],
       [ 0.0415,  1.3445,  0.324 ],
       [-0.7975,  0.3017, -0.0826],
       [-0.4329, -1.4151, -0.2774],
       [-1.1475, -0.0772, -0.2667],
       [-0.5149, -1.1784, -0.1401],
       [ 0.1993, -0.2854, -0.2114],
       [-0.432 ,  0.2143, -0.1053],
       [-0.7481, -0.384 , -0.2408],
       [ 0.8078, -0.1196, -0.2631],
       [-0.7605, -0.5792, -0.1936],
       [ 0.3237,  0.797 ,  0.217 ],
       [ 1.3089,  0.5786, -0.1887],
       [ 1.2323,  1.4421,  0.4506]])

In [7]:
num_points = points_3d.shape[0]
num_variables = 11

In [6]:
num_points

20

In [8]:

# AM = b
A = np.zeros((2*num_points, num_variables), dtype=np.float)
b = np.zeros((2*num_points), dtype=np.float)
# Form set of linear equations

In [11]:
for ix, ([u, v], [x, y, z]) in enumerate(zip(points_2d, points_3d)):
    A[2*ix, :]   = [x, y, z, 1, 0, 0, 0, 0, -u*x, -u*y, -u*z]
    A[2*ix+1, :] = [0, 0, 0, 0, x, y, z, 1, -v*x, -v*y, -v*z]
    b[2*ix]      = u
    b[2*ix+1]    = v

In [12]:
A

array([[ 1.57060000e+00, -1.49000000e-01,  2.59800000e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -1.64693116e+00,
         1.56241400e-01, -2.72426280e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.57060000e+00, -1.49000000e-01,
         2.59800000e-01,  1.00000000e+00,  5.72483700e-01,
        -5.43105000e-02,  9.46971000e-02],
       [-1.52820000e+00,  9.69500000e-01,  3.80200000e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -2.57516982e+00,
         1.63370445e+00,  6.40675020e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.52820000e+00,  9.69500000e-01,
         3.80200000e-01,  1.00000000e+00, -6.11891280e-01,
         3.88187800e-01,  1.52232080e-01],
       [-6.82100000e-01,  1.28560000e+00,  4.07800000e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
  

In [13]:
b

array([ 1.0486, -0.3645, -1.6851, -0.4004, -0.9437, -0.42  ,  1.0682,
        0.0699,  0.6077, -0.0771,  1.2543, -0.6454, -0.2709,  0.8635,
       -0.4571, -0.3645, -0.7902,  0.0307,  0.7318,  0.6382, -1.058 ,
        0.3312,  0.3464,  0.3377,  0.3137,  0.1189, -0.431 ,  0.0242,
       -0.4799,  0.292 ,  0.6109,  0.083 , -0.4081,  0.292 , -0.1109,
       -0.2992,  0.5129, -0.0575,  0.1406, -0.4527])

In [16]:
z = np.array([1,2])

In [20]:
z

array([1, 2])

In [21]:
z1 = np.array([1,2])
z1

array([1, 2])

In [22]:
k = z1.T @ z

In [23]:
k

5

In [14]:
# Solve for M
# M = (A'A)^-1.A'b
M = np.linalg.inv(A.T@A) @ A.T @ b

In [24]:
M

array([ 0.76785834, -0.49384797, -0.02339781,  0.00674445, -0.0852134 ,
       -0.09146818, -0.90652332, -0.08775678,  0.18265016,  0.29882917,
       -0.07419242])

In [25]:
# M = np.linalg.lstsq(A, b)[0]
M = np.append(M, 1).reshape((3, 4))

In [26]:
M

array([[ 0.76785834, -0.49384797, -0.02339781,  0.00674445],
       [-0.0852134 , -0.09146818, -0.90652332, -0.08775678],
       [ 0.18265016,  0.29882917, -0.07419242,  1.        ]])

In [27]:
Q = M[:, :3]

In [28]:
Q

array([[ 0.76785834, -0.49384797, -0.02339781],
       [-0.0852134 , -0.09146818, -0.90652332],
       [ 0.18265016,  0.29882917, -0.07419242]])

In [33]:
-np.linalg.inv(Q)

array([[-0.93082777,  0.14625955, -1.49352658],
       [ 0.57622846,  0.17664309, -2.34004436],
       [ 0.02935658,  1.07154387,  0.37650227]])

In [29]:
m4 = M[:, 3]

In [30]:
m4

array([ 0.00674445, -0.08775678,  1.        ])

In [31]:
cc = -np.linalg.inv(Q) @ m4

In [32]:
cc

array([-1.51263977, -2.35165965,  0.28266502])

In [36]:
# Load the data
# Mount Rushmore
pic_a = load_image('../data/Mount Rushmore/9193029855_2c85a50e91_o.jpg'); scale_a = 0.25
pic_b = load_image('../data/Mount Rushmore/7433804322_06c5620f13_o.jpg'); scale_b = 0.37
n_feat = 5e4

# Notre Dame
# pic_a = load_image('../data/Notre Dame/921919841_a30df938f2_o.jpg'); scale_a = 0.5
# pic_b = load_image('../data/Notre Dame/4191453057_c86028ce1f_o.jpg'); scale_b = 0.5
# n_feat = 8e3

# Gaudi
# pic_a = load_image('../data/Episcopal Gaudi/3743214471_1b5bbfda98_o.jpg'); scale_a = 0.8
# pic_b = load_image('../data/Episcopal Gaudi/4386465943_8cf9776378_o.jpg'); scale_b = 1.0
# n_feat = 2e4

# Woodruff
# pic_a = load_image('../data/Woodruff Dorm/wood1.jpg'); scale_a = 0.65
# pic_b = load_image('../data/Woodruff Dorm/wood2.jpg'); scale_b = 0.65
# n_feat = 5e4

pic_a = cv2.resize(pic_a, None, fx=scale_a, fy=scale_a)
pic_b = cv2.resize(pic_b, None, fx=scale_b, fy=scale_b)

In [37]:
# Finds matching points in the two images using OpenCV's implementation of ORB.
# There can still be many spurious matches, though.
points_2d_pic_a, points_2d_pic_b = get_matches(pic_a, pic_b, n_feat)

In [38]:
points_2d_pic_a

array([[531.60003662, 354.        ],
       [437.        , 270.        ],
       [799.20001221, 648.        ],
       ...,
       [984.96014404, 192.84483337],
       [ 72.        , 738.        ],
       [895.79541016, 653.93066406]])

In [40]:
len(points_2d_pic_a)

1214

In [39]:
points_2d_pic_b

array([[1076.        ,  868.        ],
       [ 374.        ,  126.        ],
       [ 110.        ,  853.        ],
       ...,
       [ 519.56134033,  716.63635254],
       [ 157.66000366,  770.38409424],
       [ 429.98181152,  777.55047607]])

In [41]:
len(points_2d_pic_b)

1214

In [34]:
F, matched_points_a, matched_points_b = sc.ransac_fundamental_matrix(points_2d_pic_a, points_2d_pic_b)

# Draw the epipolar lines on the images and corresponding matches
match_image = show_correspondence2(pic_a, pic_b,
                                   matched_points_a[:, 0], matched_points_a[:, 1],
                                   matched_points_b[:, 0], matched_points_b[:, 1])
plt.figure(); plt.imshow(match_image)
draw_epipolar_lines(F, pic_a, pic_b, matched_points_a, matched_points_b)

NameError: name 'points_2d_pic_a' is not defined